# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fac6f73d2da968a249147a67c93e1a2d630c6bb54a4616a8dc300e799bccd614ab184b9024165fc52db62a22b51f55ad96905350f9ef8f9fd361f008c56e7b8

test:
  secret_key_base: df3281e0fe7e69848fe32fbd9a875c1dd27876877e509083d153e1d464eb4097323ca242e4a5bd4a25d3597f7df4994769c345931ade5075db625d4160f35c58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
